name: Update graphs
on:
  schedule:
    - cron: '0 17 * * *'
jobs:
  update:
    name: update data
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main
        with:
          ref: master
          lfs: true
      - name: setup python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: install python and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r update/requirements.txt
      - name: run notebooks
        id: run_notebooks
        run: |
          jupyter nbconvert --to notebook --inplace --execute 0_general.ipynb
          find ./extra/*.ipynb | xargs -I'{}' jupyter nbconvert --to notebook --inplace --execute '{}'
      - name: git status
        id: git-status
        run: |
          git config --global user.email "covid-pruebas-bot@example.com"
          git config --global user.name "covid-pruebas-bot"
          echo ::set-output name=result::$(git status ./img/ | tr -d "\n" | grep -c "nothing to commit")
      - name: commit
        if: steps.git-status.outputs.result == 0
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add -A
          git commit -m "[ci] actualización"
          git push -q "https://$GH_TOKEN@github.com/pr0nstar/covid19-pruebas.git" master
